GOLD PRICE PREDICTION USING SVM

In [26]:
import pandas as pd

In [27]:
df = pd.read_csv('financial_regression.csv')

In [28]:
df.head()

,date,sp500 open,sp500 high,sp500 low,sp500 close,sp500 volume,sp500 high-low,nasdaq open,nasdaq high,nasdaq low,...,palladium high,palladium low,palladium close,palladium volume,palladium high-low,gold open,gold high,gold low,gold close,gold volume
0,2010-01-14,114.49,115.14,114.42,114.93,115646960.0,0.72,46.26,46.520,46.22,...,45.02,43.86,44.84,364528.0,1.16,111.51,112.37,110.79,112.03,18305238.0
1,2010-01-15,114.73,114.84,113.20,113.64,212252769.0,1.64,46.46,46.550,45.65,...,45.76,44.40,45.76,442210.0,1.36,111.35,112.01,110.38,110.86,18000724.0
2,2010-01-18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2010-01-19,113.62,115.13,113.59,115.06,138671890.0,1.54,45.96,46.640,45.95,...,47.08,45.70,46.94,629150.0,1.38,110.95,111.75,110.83,111.52,10467927.0
4,2010-01-20,114.28,114.45,112.98,113.89,216330645.0,1.47,46.27,46.604,45.43,...,47.31,45.17,47.05,643198.0,2.14,109.97,110.05,108.46,108.94,17534231.0

In [29]:
df.drop(columns=['date'],inplace=True)
df.drop(columns=['CPI'],inplace=True)
df.drop(columns=['us_rates_%'],inplace=True)

In [30]:
df.head()

,sp500 open,sp500 high,sp500 low,sp500 close,sp500 volume,sp500 high-low,nasdaq open,nasdaq high,nasdaq low,nasdaq close,...,palladium high,palladium low,palladium close,palladium volume,palladium high-low,gold open,gold high,gold low,gold close,gold volume
0,114.49,115.14,114.42,114.93,115646960.0,0.72,46.26,46.520,46.22,46.39,...,45.02,43.86,44.84,364528.0,1.16,111.51,112.37,110.79,112.03,18305238.0
1,114.73,114.84,113.20,113.64,212252769.0,1.64,46.46,46.550,45.65,45.85,...,45.76,44.40,45.76,442210.0,1.36,111.35,112.01,110.38,110.86,18000724.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,113.62,115.13,113.59,115.06,138671890.0,1.54,45.96,46.640,45.95,46.59,...,47.08,45.70,46.94,629150.0,1.38,110.95,111.75,110.83,111.52,10467927.0
4,114.28,114.45,112.98,113.89,216330645.0,1.47,46.27,46.604,45.43,45.92,...,47.31,45.17,47.05,643198.0,2.14,109.97,110.05,108.46,108.94,17534231.0

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3904 entries, 0 to 3903
Data columns (total 44 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   sp500 open          3719 non-null   float64
 1   sp500 high          3719 non-null   float64
 2   sp500 low           3719 non-null   float64
 3   sp500 close         3719 non-null   float64
 4   sp500 volume        3719 non-null   float64
 5   sp500 high-low      3719 non-null   float64
 6   nasdaq open         3719 non-null   float64
 7   nasdaq high         3719 non-null   float64
 8   nasdaq low          3719 non-null   float64
 9   nasdaq close        3719 non-null   float64
 10  nasdaq volume       3719 non-null   float64
 11  nasdaq high-low     3719 non-null   float64
 12  usd_chf             3694 non-null   float64
 13  eur_usd             3694 non-null   float64
 14  GDP                 57 non-null     float64
 15  silver open         3719 non-null   float64
 16  silver high         3719 non-null   float64
 17  silver low          3719 non-null   float64
 18  silver close        3719 non-null   float64
 19  silver volume       3719 non-null   float64
 20  silver high-low     3719 non-null   float64
 21  oil open            3719 non-null   float64
 22  oil high            3719 non-null   float64
 23  oil low             3719 non-null   float64
 24  oil close           3719 non-null   float64
 25  oil volume          3719 non-null   float64
 26  oil high-low        3719 non-null   float64
 27  platinum open       3719 non-null   float64
 28  platinum high       3719 non-null   float64
 29  platinum low        3719 non-null   float64
 30  platinum close      3719 non-null   float64
 31  platinum volume     3719 non-null   float64
 32  platinum high-low   3719 non-null   float64
 33  palladium open      3719 non-null   float64
 34  palladium high      3719 non-null   float64
 35  palladium low       3719 non-null   float64
 36  palladium close     3719 non-null   float64
 37  palladium volume    3719 non-null   float64
 38  palladium high-low  3719 non-null   float64
 39  gold open           3719 non-null   float64
 40  gold high           3719 non-null   float64
 41  gold low            3719 non-null   float64
 42  gold close          3719 non-null   float64
 43  gold volume         3719 non-null   float64
dtypes: float64(44)
memory usage: 1.3 MB

In [32]:
df.drop(columns=['GDP'],inplace=True)

In [33]:
df.head()

,sp500 open,sp500 high,sp500 low,sp500 close,sp500 volume,sp500 high-low,nasdaq open,nasdaq high,nasdaq low,nasdaq close,...,palladium high,palladium low,palladium close,palladium volume,palladium high-low,gold open,gold high,gold low,gold close,gold volume
0,114.49,115.14,114.42,114.93,115646960.0,0.72,46.26,46.520,46.22,46.39,...,45.02,43.86,44.84,364528.0,1.16,111.51,112.37,110.79,112.03,18305238.0
1,114.73,114.84,113.20,113.64,212252769.0,1.64,46.46,46.550,45.65,45.85,...,45.76,44.40,45.76,442210.0,1.36,111.35,112.01,110.38,110.86,18000724.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,113.62,115.13,113.59,115.06,138671890.0,1.54,45.96,46.640,45.95,46.59,...,47.08,45.70,46.94,629150.0,1.38,110.95,111.75,110.83,111.52,10467927.0
4,114.28,114.45,112.98,113.89,216330645.0,1.47,46.27,46.604,45.43,45.92,...,47.31,45.17,47.05,643198.0,2.14,109.97,110.05,108.46,108.94,17534231.0

In [34]:
df.shape

(3904, 43)

In [35]:
df.isnull().sum()

sp500 open            185
sp500 high            185
sp500 low             185
sp500 close           185
sp500 volume          185
sp500 high-low        185
nasdaq open           185
nasdaq high           185
nasdaq low            185
nasdaq close          185
nasdaq volume         185
nasdaq high-low       185
usd_chf               210
eur_usd               210
silver open           185
silver high           185
silver low            185
silver close          185
silver volume         185
silver high-low       185
oil open              185
oil high              185
oil low               185
oil close             185
oil volume            185
oil high-low          185
platinum open         185
platinum high         185
platinum low          185
platinum close        185
platinum volume       185
platinum high-low     185
palladium open        185
palladium high        185
palladium low         185
palladium close       185
palladium volume      185
palladium high-low    185
gold open             185
gold high             185
gold low              185
gold close            185
gold volume           185
dtype: int64

In [36]:
df = df.fillna(df.mean() )

In [37]:
df.isnull().sum()

sp500 open            0
sp500 high            0
sp500 low             0
sp500 close           0
sp500 volume          0
sp500 high-low        0
nasdaq open           0
nasdaq high           0
nasdaq low            0
nasdaq close          0
nasdaq volume         0
nasdaq high-low       0
usd_chf               0
eur_usd               0
silver open           0
silver high           0
silver low            0
silver close          0
silver volume         0
silver high-low       0
oil open              0
oil high              0
oil low               0
oil close             0
oil volume            0
oil high-low          0
platinum open         0
platinum high         0
platinum low          0
platinum close        0
platinum volume       0
platinum high-low     0
palladium open        0
palladium high        0
palladium low         0
palladium close       0
palladium volume      0
palladium high-low    0
gold open             0
gold high             0
gold low              0
gold close            0
gold volume           0
dtype: int64

In [41]:
df.columns

Index(['sp500 open', 'sp500 high', 'sp500 low', 'sp500 close', 'sp500 volume',
       'sp500 high-low', 'nasdaq open', 'nasdaq high', 'nasdaq low',
       'nasdaq close', 'nasdaq volume', 'nasdaq high-low', 'usd_chf',
       'eur_usd', 'silver open', 'silver high', 'silver low', 'silver close',
       'silver volume', 'silver high-low', 'oil open', 'oil high', 'oil low',
       'oil close', 'oil volume', 'oil high-low', 'platinum open',
       'platinum high', 'platinum low', 'platinum close', 'platinum volume',
       'platinum high-low', 'palladium open', 'palladium high',
       'palladium low', 'palladium close', 'palladium volume',
       'palladium high-low', 'gold open', 'gold high', 'gold low',
       'gold close', 'gold volume'],
      dtype='object')

In [42]:
SVR(kernel="rbf")

SVR()

In [43]:
X = df.drop("gold close", axis=1)
y = df["gold close"]

In [44]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [45]:
from sklearn.preprocessing import StandardScaler

scaler_X = StandardScaler()
scaler_y = StandardScaler()

X_train_scaled = scaler_X.fit_transform(X_train)
X_test_scaled = scaler_X.transform(X_test)

y_train_scaled = scaler_y.fit_transform(
    y_train.values.reshape(-1, 1)
).ravel()

In [46]:
from sklearn.svm import SVR

svr = SVR(
    kernel="rbf",
    C=100,
    gamma=0.1,
    epsilon=0.1
)

svr.fit(X_train_scaled, y_train_scaled)

SVR(C=100, gamma=0.1)

In [47]:
y_pred_scaled = svr.predict(X_test_scaled)

In [48]:
y_pred = scaler_y.inverse_transform(
    y_pred_scaled.reshape(-1, 1)
).ravel()

In [49]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print("MAE :", mae)
print("RMSE:", rmse)
print("R²  :", r2)

MAE : 2.480443375886909
RMSE: 4.482073760581286
R²  : 0.9755020777823334

In [50]:
pd.DataFrame({
    "Actual Gold Price": y_test.values[:10],
    "Predicted Gold Price": y_pred[:10]
})

   Actual Gold Price  Predicted Gold Price
0           117.5645            117.551446
1           188.1800            185.689822
2           119.3400            119.010433
3           122.8500            123.026008
4           104.1800            103.514095
5           172.5800            169.933388
6           121.6900            124.737411
7           181.6400            183.770927
8           142.3800            142.415990
9           119.3800            119.491974